repos:
  # For general code format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.8
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: tflint
      - id: terraform-validate
      - id: terraform-fmt
