name: check

on:
  workflow_dispatch:
  pull_request:
    branches: ["*"]
    paths:
      - "terraform/**"

env:
  TF_LOG: INFO
  TF_INPUT: false
  PYTHON_VERSION: "3.12"
  TERRAFORM_VERSION: "1.9.7"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip" # caching pip dependencies

        # Install the selected version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run pre-commit
        run: pre-commit run --all-files
